# Generated by Django 3.2.4 on 2021-07-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=30, null=True)),
                ('aName', models.CharField(max_length=20, null=True)),
                ('aPwd', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
