# Generated by Django 3.2.4 on 2021-07-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='MyAdmin',
        ),
    ]
