# Generated by Django 3.2.5 on 2021-07-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20210701_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myadmin',
            name='aEmail',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
