# Generated by Django 3.2.3 on 2021-06-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=40)),
                ('subject', models.CharField(default='', max_length=20)),
                ('message', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
