# Generated by Django 3.2.3 on 2021-06-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210617_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('whatFor', models.CharField(max_length=40, null=True)),
                ('quantity', models.CharField(default='1', max_length=20, null=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('adharcard', models.ImageField(null=True, upload_to='adharcard')),
                ('prescription', models.ImageField(null=True, upload_to='prescription')),
                ('status', models.CharField(default='pending', max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
