# Generated by Django 3.2.3 on 2021-06-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='city_state',
        ),
    ]
