# Generated by Django 3.2.3 on 2021-06-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210629_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='adharcard',
            field=models.ImageField(null=True, upload_to='adharcard'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='prescription',
            field=models.ImageField(null=True, upload_to='prescription'),
        ),
    ]
