# Generated by Django 3.2.3 on 2021-06-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210617_0906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
