# Generated by Django 3.2.3 on 2021-06-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210629_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='adharcard',
            field=models.ImageField(null=True, upload_to='images/adharcard'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='prescription',
            field=models.ImageField(null=True, upload_to='images/prescription'),
        ),
    ]
